### ISSUE TITLE
Flink wordcount experiment with YARN

### ISSUE THREAD

**Issue by noproblem666** [peelframework/peel#93] opened 2016-06-29 10:43 UTC
Hi,
we want to run the flink wordcount experiment on our cluster on the top of YARN and HDFS. For this we added another dependency to our` flink.0.10.2` bean in the` systems.xml`. But this does not work properly. Can you give us a hint, how we have to configure the sytems.xml to run flink on YARN and HDFS.

Thanks,
Robert

**Comment by aalexandrov** [comment] 2016-07-04 17:39
Can you point me to a repository that contains the experiment configuration?

**Comment by noproblem666** [comment] 2016-07-06 13:59
Thanks for your response @aalexandrov and sorry for my delay! 

You can find our configuration files here: [peel-wordcount/config](https://github.com/noproblem666/peel-wordcount/tree/master/config)

**Comment by aalexandrov** [comment] 2016-07-06 14:35
Can you run `exp:setup wordcount.default wordcount.flink` and monitor the status of the configured systems (run `jps`, open the webinterface to check whether all the systems have started properly).

You can also post the output of the Peel command (also written in `log/peel.log` here).

**Comment by noproblem666** [comment] 2016-07-12 12:26
This is the Output, when I run `exp:setup wordcount.default wordcount.flink`: [log exp:setup](https://gist.github.com/noproblem666/31d26b114b7a075d1c79ca4e2bec58e7)

With this command `peel` updates the `fs.default.name` value in the `core-site.xml` file to `localhost:9000`. Therefore no nodes can connect to the master. 

When I run `sys:setup flink-0.10.2` with the same configurationI will get this output: [log sys:setup](https://gist.github.com/noproblem666/6b52025bec43cc01172b62ee542858b0)

**One remark:** The YARN extension implementation starts YARN with `yarn-daemon.sh start resourcemanager` and `yarn-daemon.sh start nodemanager` script. It seems that this script will start the yarn daemons on localhost only. This is what happened on our experiment cluster. 

In my opinion, `start-yarn.sh` would be the better way.

We are grateful for any feedback.

**Comment by aalexandrov** [comment] 2016-07-12 13:05
> With this command peel updates the fs.default.name value in the core-site.xml file to localhost:9000. Therefore no nodes can connect to the master. 

@noproblem666 It seems that you have not set-up an environment configuration for your test cluster. You can take a look at 

```
https://github.com/stratosphere/peelconfig.cloud-11
https://github.com/stratosphere/peelconfig.cloud-7
```

Which we use at DIMA and adapt them.

> The YARN extension implementation starts YARN with yarn-daemon.sh start resourcemanager and yarn-daemon.sh start nodemanager script. It seems that this script will start the yarn daemons on localhost only. This is what happened on our experiment cluster.
> 
> In my opinion, start-yarn.sh would be the better way.

Indeed, this sounds like a bug in the Yarn implementation. 

@joh-mue, @lauritzthamsen did you actually use the Yarn setup on Wally at CIT?

**Comment by aalexandrov** [comment] 2016-07-12 13:13
> With this command peel updates the fs.default.name value in the core-site.xml file to localhost:9000. Therefore no nodes can connect to the master. 

Looking at both [your config scripts](https://github.com/noproblem666/peel-wordcount/tree/master/config) and [the `sys:setup` log output](https://gist.github.com/noproblem666/31d26b114b7a075d1c79ca4e2bec58e7), it seems to me that the `fs.default.name` should be set to `fs.default.name = "hdfs://"${runtime.hostname}":8020/"` (as defined in `hadoop-2.conf` which is included from `hdfs-2.7.1.conf`).

**Comment by aalexandrov** [comment] 2016-07-12 13:16
This could be due to a merging issue of the `system.hadoop-2.config` namespace after including `yarn.conf`.

**Comment by aalexandrov** [comment] 2016-07-12 13:27
OK I think I found the root cause:

```
16-07-06 16:43:21 [INFO] Loading configuration for experiment 'wordcount.flink'
16-07-06 16:43:21 [INFO] +-- Loading resource reference.peel.conf
16-07-06 16:43:21 [INFO] +-- Loading resource reference.hdfs-2.7.1.conf
16-07-06 16:43:21 [INFO] +-- Loading file /usr/local/share/peel/peel-wordcount/config/hdfs-2.7.1.conf
16-07-06 16:43:22 [INFO] +-- Skipping file /usr/local/share/peel/peel-wordcount/config/hosts/flink-s0/hdfs-2.7.1.conf (does not exist)
16-07-06 16:43:22 [INFO] +-- Loading resource reference.yarn-2.7.1.conf
16-07-06 16:43:22 [INFO] +-- Loading file /usr/local/share/peel/peel-wordcount/config/yarn-2.7.1.conf
16-07-06 16:43:22 [INFO] +-- Skipping file /usr/local/share/peel/peel-wordcount/config/hosts/flink-s0/yarn-2.7.1.conf (does not exist)
16-07-06 16:43:22 [INFO] +-- Loading resource reference.flink-0.10.2.conf
16-07-06 16:43:22 [INFO] +-- Loading file /usr/local/share/peel/peel-wordcount/config/flink-0.10.2.conf
16-07-06 16:43:22 [INFO] +-- Skipping file /usr/local/share/peel/peel-wordcount/config/hosts/flink-s0/flink-0.10.2.conf (does not exist)
16-07-06 16:43:22 [INFO] +-- Loading file /usr/local/share/peel/peel-wordcount/config/application.conf
16-07-06 16:43:22 [INFO] +-- Skipping file /usr/local/share/peel/peel-wordcount/config/hosts/flink-s0/application.conf (does not exist)
16-07-06 16:43:22 [INFO] +-- Loading experiment configuration
16-07-06 16:43:22 [INFO] +-- Loading current runtime values as configuration
16-07-06 16:43:22 [INFO] +-- Loading system properties as configuration
16-07-06 16:43:22 [INFO] `-- Resolving configuration
```

The defaults from [`reference.yarn-2.7.1.conf`](https://github.com/peelframework/peel/blob/master/peel-extensions/src/main/resources/reference.yarn-2.7.1.conf) (which transitively include [`reference.hadoop-2.x.conf`](https://github.com/peelframework/peel/blob/master/peel-extensions/src/main/resources/reference.hadoop-2.x.conf) are loaded **after** `config/hdfs-2.7.1.conf`, so you are using the default hdfs-related values.

A quickfix might be to change the order of dependencies declaration in your experiment bean:

```xml
<!-- Flink (overridden 'flink-0.10.2' bean that depends on 'hdfs-2.7.1') -->
<bean id="flink-0.10.2" class="org.peelframework.flink.beans.system.Flink" parent="system">
  <constructor-arg name="version" value="0.10.2"/>
  <constructor-arg name="configKey" value="flink" />
  <constructor-arg name="lifespan" value="EXPERIMENT"/>
  <constructor-arg name="dependencies">
    <set value-type="org.peelframework.core.beans.system.System">
        <ref bean="yarn-2.7.1"/>
        <ref bean="hdfs-2.7.1"/>
    </set>
  </constructor-arg> 
</bean>
```

For a better solution, however, the order in which 'reference.*', bundle-specific, and host-specific config is loaded should dominate the systems, e.g.

```
for each layer (reference, bundle, host-specific)
  for each dependent system
    load config
```

rather than what is used before

```
for each dependent system
  for each layer (reference, bundle, host-specific)
    load config
```

However, I have to think about this first, as it might break the API.

**Comment by fschueler** [comment] 2016-07-18 15:27
I just hit the same problem and for me the solution was to include the parameters from the `hdfs-2.7.1.conf` also in the `yarn-2.7.1.conf`, overwriting the hadoop defaults again.

**Comment by joh-mue** [comment] 2016-07-21 11:43
i believe that is what I did too. It's been a while though.

**Comment by noproblem666** [comment] 2016-07-26 14:37
Thanks for your feedback! 

Yes, the solution @fschueler mentioned works for me also.  Nevertheless this should not the desired behaviour, right? 

If I change the order of dependency declaration in `systems.xml` like @aalexandrov mentioned to the following, it will work also:

```xml
<!-- Flink (overridden 'flink-0.10.2' bean that depends on 'hdfs-2.7.1') -->
    <bean id="flink-0.10.2" class="org.peelframework.flink.beans.system.Flink" parent="system">
        <constructor-arg name="version" value="0.10.2"/>
        <constructor-arg name="configKey" value="flink" />
        <constructor-arg name="lifespan" value="EXPERIMENT"/>
        <constructor-arg name="dependencies">
            <set value-type="org.peelframework.core.beans.system.System">
                <ref bean="hdfs-2.7.1"/>
                <ref bean="yarn-2.7.1"/>
            </set>
        </constructor-arg>
    </bean>
```

In this case the `yarn-2.7.1.conf` requires YARN related configuration parameters only. 

I also changed `Yarn.scala` extension. It uses `start-yarn.sh` and `stop-yarn.sh` shell scripts to start/stop the YARN daemons instead of `yarn-daemon.sh`. You will find the changes [here](https://github.com/noproblem666/peel/commit/6868bafee192d75fa732a50d98dcfa3ad073e5ee).

The next thing is to start a YARN session for Flink. I will come back to that point within the next days.

Thanks a lot for your help!

**Comment by noproblem666** [comment] 2016-08-01 13:16
I would like to come back to my previous post. 

We want to run Flink on the top of YARN. To do this, we need to start the `yarn-session.sh` script from the Flink system directory after YARN is started on the cluster. 

Starting `yarn-session.sh` instead of `start-cluster.sh` is not implemented in the flink class so far. Are you planning to add YARN support to the Flink extension soon? 

Like the feature for clusters with no shared disk in #92, we would like to add support for YARN to the flink class in a similar way with a config parameter in `application.conf`.

Do you have any concerns doing this or do you have other ideas to start Flink with YARN via peel framework?  

Thanks a lot!

**Comment by aalexandrov** [comment] 2016-08-01 14:02
> Starting yarn-session.sh instead of start-cluster.sh is not implemented in the flink class so far. Are you planning to add YARN support to the Flink extension soon?

This is not supported yet, but contributions are welcome.

**Comment by aalexandrov** [comment] 2016-08-01 14:18
@noproblem666: To get a quick prototype that can be verified against an existing bundle quickly, you can 

1. subclass Flink and, 
1. add the new class in your `$bundle-peelextensions` package, and 
1. modify the setup / teardown logic in the subclass.

Then configure modified flink bean as follows:

```scala
  @Bean(name = Array("flink-1.0.3-yarn"))
  def `flink-1.0.3`: Flink = new FlinkOnYarn(
    version      = "1.0.3",
    configKey    = "flink",
    lifespan     = Lifespan.EXPERIMENT,
    dependencies = Set(ctx.getBean("hdfs-2.7.1", classOf[HDFS2]), ctx.getBean("yarn-2.7.1", classOf[Yarn])),
    mc           = ctx.getBean(classOf[Mustache.Compiler])
  )

**Comment by aalexandrov** [comment] 2016-09-07 09:13
The issues with the Yarn start/stop and with the dependency resolution should be resolved with Peel 1.1.0. 

Can you revert the workaround solution, validate and report, so we can close this?

**Comment by noproblem666** [comment] 2016-09-22 13:40
Yes, Yarn works fine now and the order of dependencies is resolved for me. You can close this issue and #96 also I think. Thanks! 👍 

For the Flink on Yarn problem I will open a new issue when I have some code to share. :-) 

Thanks again!

**Comment by aalexandrov** [comment] 2016-09-22 13:56
@noproblem666 @FelixNeutatz perhaps you can join forces here, we already merged some Yarn related stuff in the master:

https://github.com/peelframework/peel/commit/c68852a1afd49fe90ffa905aa201e42fb6c2ed88

**Closed** 2016-09-22 13:57 UTC
Labels: help wanted
